version: '3'
services:
  db:
    image: postgres:14.4-alpine
    container_name: postgres_1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testdb