spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

exception_message: Сущность не найдена, проверьте id=
time_period: 900
cron_interval: 0 0/5 8-22 * * ?
check_interval: 10
only_weekday: true
api_name: api/v2
company_open: 8
company_close: 20
access_day_interval: 7
access_arrived_time: 60
default_password: passw0rd


jwt:
  secret_access_key: Pax Pamir
  secret_refresh_key: Pax Renaissance
  life_time_access: 10
  life_time_refresh: 60
  subject: User details
