spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
#    show-sql: true
    flyway:
      baseline-on-migrate: true
#    properties:
#      hibernate:
#        format_sql: true

exception_message: Сущность не найдена, проверьте id=
invalid_role: У user#%d недопустимая роль - %s

time_period: 15
cron_interval: 0 0/5 8-22 * * ?
check_interval: 10
only_weekday: true
api_name: api/v2

jwt:
  secret_access_key: Pax Pamir
  secret_refresh_key: Pax Renaissance
  life_time_access: 3
  life_time_refresh: 60
  subject: User details
